typography_spectrum: 0.46352
color:
  brandColors:
    - '#00aae2'
    - '#007e9d'
    - '#004659'
    - '#e9ccac'
    - '#817268'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.9748706661630422
  rhythmicContrast: 0.8810483161360025
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75363
analytics:
  google: null
  facebook: null
  twitter: null
name: Kerri Lake
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Universal Facilitation
purpose: []
